### ISSUE TITLE
Add Tomcat 9.0.35 To The Image

### ISSUE THREAD

**Issue by hoshposh** [caf-archive/opensuse-tomcat-image#32]
The version of Tomcat supplied in the base image is `v9.0.26`, while the current version is `v9.0.35`.

The [Tomcat changelog](https://tomcat.apache.org/tomcat-9.0-doc/changelog.html) shows there have been numerous fixes in the `catalina` module alone, so not sure if it is time to bring this image up to date?

**Comment by michael-bryson** [comment]
Created https://portal.digitalsafe.net/browse/SCMOD-9768 in JIRA to track this.

**Comment by michael-bryson** [comment]
@hoshposh 
Hi Lyndon,

I have updated this image to Tomcat version 9.0.35.

As this has not been released yet you need to pull it from the prereleases repository.

    docker login dockerhub-private.svsartifactory.swinfra.net
    docker image pull dockerhub-private.svsartifactory.swinfra.net/cafinternal/prereleases:opensuse-tomcat-5.0.0-SNAPSHOT

- Obviously you only need to login if you haven't already done so in the past.
- You can login with either SWINFRA domain or CORPDOM domain credentials.
  - To use SWINFRA credentials use your swinfra logon name as the username
  - To use CORPDOM credentials use the full corpdom user principal name as the username

Thanks,
Michael
