### ISSUE TITLE
Trace & debug log messages suppressed

### ISSUE THREAD

**Issue by dhsmith1001** [caf-archive/opensuse-tomcat-image#35]
In testing simple war applications that log various types of messages, I found that debug and trace level messages are suppressed. I tried setting CAF_LOG_LEVEL to TRACE, but that only produced debug & trace output from the caf-logging framework itself, not any other loggers.

I couldn't see anything in the logback.xml that would suppress these messages, i.e. an appender set to INFO level as can happen with log4j.

**Comment by dermot-hardy** [comment]
https://portal.digitalsafe.net/browse/SCMOD-9964

**Comment by dermot-hardy** [comment]
@dhsmith1001 Which logging framework are you trying to use?  And are you using a logging facade?

**Comment by dhsmith1001** [comment]
Using logback, with slf4j-api for creating loggers via org.slf4j.LoggerFactory. I have a logging framwork that consists of com.netiq.ism:logging-common & com.netiq.ism:logging-logback. The logging-logback module is new, but I have implemented logging-log4j, logging-jdk, logging-slf4j, etc. I have tested the logging-logback module on a plain tomcat that's been instrumented for logback logging similarly to opensuse-tomcat-image, and the logging works correctly there too.

**Comment by dermot-hardy** [comment]
Try adding this dependency to the war application:

    <dependency>
        <groupId>com.github.cafapi.logging</groupId>
        <artifactId>caf-logging-logback</artifactId>
        <version>1.2.0-67</version>
        <scope>runtime</scope>
    </dependency>

**Comment by dhsmith1001** [comment]
I had already done that prior to writing the bug. It helped in that the log message format from my test WARs started printing in the same layout as all of the other messages, so it did help. An example log message, along with one from the server, are below.

[19:05:10.116Z #1f3.001 INFO  -            -   ] o.a.c.startup.HostConfig: Deploying web application directory [/usr/share/tomcat/webapps/ROOT]
[19:05:18.450Z #c60.055 ERROR -            -   ] c.n.l.l.test1.LoggingServlet1: [TOMCAT-T1] Test Error Message 0 from thread ERROR_THREAD

The access log shows that my servlet was called with the debug parameter, but no subsequent debug messages printed

[19:05:48.548Z #1f3.020 INFO  -            -   ] AccessLog: 172.17.0.1 - "GET /logback-test-webapp2-1.2.1-SNAPSHOT/loggingservlet2?action=debug HTTP/1.1" 200 - "http://localhost:8080/logback-test-webapp2-1.2.1-SNAPSHOT/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

**Comment by dhsmith1001** [comment]
OK, I have to retract this bug, sorry! I figured out it was a configuration issue in my test WARs. I have the logging working correctly now and printing trace & debug messages.
